---
title: "modeling cleaning"
date: "2026-05-05"
---

for some pre-cleaning of modeling data from googlesheets

re-run whenever the gsheets gets updated

# loading & init

```{r message = FALSE}
library(tidyverse)
library(googlesheets4)

#library(lubridate) # for time stuff
#conflicts_prefer(dplyr::filter) # if necessary

here::i_am("scripts/import.Rmd")
library(here)
```

```{r}
raw <- read.csv(here("data/raw/gsheets-import.csv"))

df <- raw
```

## futzing

```{r}
# format numeric and date cols
df <- df %>%
  mutate(across(starts_with("date."), ~ str_c(., "/2026")),
         across(starts_with("date"), as.Date, format = "%m/%d/%Y"),
         across(c("id", starts_with(c("mass", "date"))), as.numeric)) %>% 
  rename_with(~ paste0("j", .x), starts_with("date"))
```


## export
```{r}
today <- format(Sys.time(), "%y%m%d-%H%M")

# make a new "export" object
export <- df %>%
  select(-c(starts_with(c("h", "time")), matches(".*\\.st"),
            jdate.15))

write.csv(raw, file = paste0(here("data/raw/"), "dev", today, ".csv"), row.names = FALSE)
write.csv(export, file = paste0(here("data/clean/"), "dev.csv"), row.names = FALSE)
```

## cleanup
```{r}
rm(today)

rm(raw, df, export)
```